variables:
  IMAGE_NAME: registry.gitlab.com/musicray/core
  DOCKER_DRIVER: overlay

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -t $IMAGE_NAME:ci-$CI_PIPELINE_ID .
    - docker push $IMAGE_NAME:ci-$CI_PIPELINE_ID