version: '2'
services:
  postgres:
    image: postgres:9.6

    environment:
      - "POSTGRES_DB=mray_core"
    network_mode: host

  consul:
    image: consul
    network_mode: host

    command: consul agent -server -bootstrap -ui -client 0.0.0.0 -data-dir=/consul/data
  mray:
    build: .
    network_mode: host
    ports:
      - 8080:8080