version: 2
jobs:
  build:
    working_directory: ~/mray-core
    docker:
      - image: openjdk:8
    environment:
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          key: mray-core-gradle-{{ checksum "build.gradle" }}
      - run: |
          apt update && apt install postgresql-9.4 postgresql-contrib-9.4 -y
          echo "host    all             all             127.0.0.1/32            trust" > /etc/postgresql/9.4/main/pg_hba.conf
          service postgresql start
          createdb -U postgres -h 127.0.0.1 mray_core_test
      - run: |
          ./gradlew build
          rm build/dist/*.original
      - save_cache:
          key: mray-core-gradle-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle
            - ~/.embedmongo
      - save_cache:
          key: mray-core-{{ .Revision }}
          paths:
            - ~/mray-core/build/dist
      - store_artifacts:
          path: ~/mray-core/build/dist
          destination: mray-core
  deploy:
    working_directory: ~/mray-core
    docker:
      - image: docker:git
    environment:
      TERM: dumb
      IMAGE_NAME: quay.io/mray/core
    steps:
      - checkout
      - restore_cache:
          key: mray-core-{{ .Revision }}
      - setup_remote_docker
      - run:
          name: Push docker image
          command: |
          docker build -t yadda/lucerne:latest .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push yadda/lucerne:latest