version: 2
jobs:
  build:
    working_directory: ~/mray-core
    docker:
      - image: openjdk:8
    environment:
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          key: mray-core-gradle-{{ checksum "build.gradle" }}
      - run: |
          apt update && apt install postgresql-9.4 postgresql-contrib-9.4 -y
          echo "host    all             all             127.0.0.1/32            trust" > /etc/postgresql/9.4/main/pg_hba.conf
          service postgresql start
          createdb -U postgres -h 127.0.0.1 mray_core_test
      - run: |
          ./gradlew build
          rm build/dist/*.original
      - save_cache:
          key: mray-core-gradle-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle
            - ~/.embedmongo
      - save_cache:
          key: mray-core-{{ .Revision }}
          paths:
            - ~/mray-core/build/dist
      - store_artifacts:
          path: ~/mray-core/build/dist
          destination: mray-core
      - run:
          name: Trigger deployment
          command: |
                if [ "${CIRCLE_BRANCH}" == "master" ]; then
                  curl -u ${CIRCLE_API_TOKEN}: \
                    -d build_parameters[CIRCLE_JOB]=deploy \
                    https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH
                fi
  deploy:
    working_directory: ~/mray-core
    docker:
      - image: docker:git
    environment:
      TERM: dumb
      IMAGE_NAME: quay.io/mray/core
    steps:
      - checkout
      - restore_cache:
          key: mray-core-{{ .Revision }}
      - setup_remote_docker
      - run:
          name: Build docker image
          command: |
            docker login -u="mray+ci" -p="$REGISTRY_PASSWORD" quay.io
            docker build -t $IMAGE_NAME:ci-$CIRCLE_BUILD_NUM -f ci.Dockerfile .
            docker tag $IMAGE_NAME:ci-$CIRCLE_BUILD_NUM $IMAGE_NAME:latest
      - run:
          name: Push docker image
          command: |
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:ci-$CIRCLE_BUILD_NUM